### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by lvchuandong** [synsin0/EFFOcc#1]
Excellent work. I want to know if your model with a backbone of Swin-B was also trained on 2080Ti.

**Comment by synsin0** [comment]
My original swin-b experiment is conducted with 4 A6000 with batch per gpu 4. I test training with 8 2080TI with batch per gpu 1 and it works normally. The configuration is the same with training with larger memory GPUs: image size 512x1408. Swin-B with no frozen stages (frozen_stages=-1), SECOND with voxel_size=[0.05,0.05,0.16]. We use checkpointing (with_cp=True) in both Swin-B image backbone and SECOND point cloud BEV backbone. The memory is 10.4G at max while the upper limit of 2080TI is 10.8G. We do not use mixed precision FP16 (fp16=dict(loss_scale='dynamic') is not used.).
