### ISSUE TITLE
About Simple Seg head

### ISSUE THREAD

**Issue by White-Sun** [synsin0/EFFOcc#2]
How did 'Simple Seg head' achieve dimension upgrading,  which 2d bev-feat to 3d occ-pred?

**Comment by synsin0** [comment]
The dimension upgrading is very similar to FlashOcc's practice (https://github.com/Yzichen/FlashOCC), the last nn.Linear layer remaps the feature channel to num_class * height_channel, then permute height_channel to h, w, l and num_class channel to the last.

**Comment by White-Sun** [comment]
> The dimension upgrading is very similar to FlashOcc's practice (https://github.com/Yzichen/FlashOCC), the last nn.Linear layer remaps the feature channel to num_class * height_channel, then permute height_channel to h, w, l and num_class channel to the last.

Thanks
