### ISSUE TITLE
What type of GPU was used when testing FPS in the experiment?

### ISSUE THREAD

**Issue by ZYang2077** [synsin0/EFFOcc#4]
Excellent work! But I have a question as the title, in TABLE III, what type of GPU was used when testing FPS in the experiment?
In addition, the paper claims that RadOcc's inference speed is obtained from the RadOcc paper, but the RadOcc paper also does not mention the type of GPU used for inference.

**Comment by synsin0** [comment]
I use a single A6000 to test FPS in the experiment. Since RadOcc does not open its code and does not mention its GPU used. I obtain the inference speed from the supplementary material of RadOcc.
